!function(e){var t={};function n(r){if(t[r])return t[r].exports;var s=t[r]={i:r,l:!1,exports:{}};return e[r].call(s.exports,s,s.exports,n),s.l=!0,s.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var s in e)n.d(r,s,function(t){return e[t]}.bind(null,s));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s="./dev/main.js")}({"./dev/main.js":
/*!*********************!*\
  !*** ./dev/main.js ***!
  \*********************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _sass_style_scss__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./sass/style.scss */ "./dev/sass/style.scss");\n/* harmony import */ var _sass_style_scss__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_sass_style_scss__WEBPACK_IMPORTED_MODULE_0__);\n\n\n/**\n * Smooth scrolling\n */\n$("a[href*=\'#\']").on("click", function (e) {\n\te.preventDefault();\n\n\tif ($(e.target.hash).offset() !== undefined) {\n\t\tlet headerHeight = $("header").height();\n\t\t$("body,html").animate({\n\t\t\tscrollTop: $(e.target.hash).offset().top\n\t\t}, 500);\n\t}\n});\n/**\n * Mobile header\n */\n$(".mobile-navigation").on("touchmove", function (e) {\n\te.preventDefault();\n});\n$(".nav-toggle, .mobile-menu li").on("click", function (e) {\n\t$(".nav-toggle").toggleClass("is-active");\n\t$(".mobile-navigation").toggleClass("is-active");\n});\n\n(function () {\n\t$(".js-top").on("click", function (e) {\n\t\t$("body,html").animate({\n\t\t\tscrollTop: 0\n\t\t}, 500);\n\t});\n})();\n\n//# sourceURL=webpack:///./dev/main.js?')},"./dev/sass/style.scss":
/*!*****************************!*\
  !*** ./dev/sass/style.scss ***!
  \*****************************/
/*! no static exports found */function(module,exports,__webpack_require__){eval("// extracted by mini-css-extract-plugin\n\n//# sourceURL=webpack:///./dev/sass/style.scss?")}});
//# sourceMappingURL=script.js.map